### ISSUE TITLE
Do samplers on Optuna Hub support distributed optimisation?

### ISSUE THREAD

**Issue by jt269** [optuna/optunahub-registry#148]
### Expected behavior

Hello,

Not a bug but a general question, do samplers hosted on Optuna Hub support distributed optimisation. I have tried some samplers such as INGO and they do not work with distributed optimisation.

I have tried to find if this is an inherent property of these samplers but could not find it in the docs etc.

Thanks

### Environment

.

### Error messages, stack traces, or logs

```shell
.
```

### Steps to reproduce

.

**Comment by F18** [comment]
I am wondering the same thing. For example, the HEBO optimizer converges significantly faster if it can be parallelized. In the original HEBO package this is accomplished by passing `n_suggestions` to `HEBO.suggest()` as shown here: https://hebo.readthedocs.io/en/latest/optimisation.html

Parallel HEBO example (from documentation):
```
hebo_batch = HEBO(space, model_name = 'gpy', rand_sample = 4)
for i in range(16):
    rec_x = hebo_batch.suggest(n_suggestions=8)
    hebo_batch.observe(rec_x, obj(rec_x))
    print('Iter %d, best_y = %.2f' % (i, hebo_batch.y.min()))
```
In the above example, 8 processes are run in parallel for each batch, and 16 batches are performed in total. By contrast, to run HEBO in serial, we would simply pass `n_suggestions=1`.

When using the HEBO Sampler through Optuna Hub, how can we reproduce the Parallel HEBO example above? In other words, if we start an RDB server and share the same study among multiple processes running HEBO, let's say 8 processes, is it equivalent to the parallel HEBO example above?

**Comment by F18** [comment]
**Update:** Using `n_jobs=8` in optuna's `Study.optimize()` to run in parallel (instead of using process-based parallelization) seems to be working for HEBO.

**Comment by y0z** [comment]
Generally, support for distributed optimization and other features depends on each sampler since samplers in OptunaHub are developed by individual contributors. Just to let you know, pull requests to enhance samplers are always welcome.

Difference between Optuna and OptunaHub
- Optuna: Committers maintain and develop samplers under quality control, including parallelization support.
- OptunaHub: Samplers are developed by individual contributors. This allows the provision of various samplers, including state-of-the-art methods as soon as possible, domain-specific niche methods, etc. The quality of each sampler is dependent on the implementer.
